### PR TITLE
Fixes #834 : error reportfile without directory specified

### LINKED ISSUE #834: Using option report with just a filename results in exception
When I run the dotnet format command with the report option, and I specify only a filename, the tool ends with an exception. Expected behaviour is that the report file is generated in the current directory.

Command:
```cmd
C:\Temp>dotnet format C:\path-to\my-repository\ --folder --check --report dotnet-format-report.json
```

Error:
```
Unhandled exception: System.ArgumentException: Path cannot be the empty string or all whitespace. (Parameter 'path')
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.CodeAnalysis.Tools.ReportWriter.Write(String reportPath, IEnumerable`1 formattedFiles, ILogger logger) in /_/src/ReportWriter.cs:line 23
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, Boolean createBinaryLog) in /_/src/CodeFormatter.cs:line 107
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, Boolean folder, String fixStyle, String fixAnalyzers, String verbosity, Boolean check, String[] include, String[] exclude, String report, Boolean includeGenerated, IConsole console) in /_/src/Program.cs:line 150
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### PR DESCRIPTION
**Pull request by Styxxy**
Fixes #834

### CODE REVIEW

File: src/ReportWriter.cs [hunk 1]
```diff
@@ -15,6 +15,12 @@ public static void Write(string reportPath, IEnumerable<FormattedFile> formatted
             var reportFilePath = GetReportFilePath(reportPath);
             var reportFolderPath = Path.GetDirectoryName(reportFilePath);
 
+            // If no folder path is specified to the report path, set it to "." (which is the current working directory)
+            if (string.Empty.Equals(reportFolderPath, StringComparison.OrdinalIgnoreCase))
+            {
+                reportFolderPath = ".";
```
Comment (JoeRobich) [inline src/ReportWriter.cs:21]: Perhaps, checking `!string.IsNullOrEmpty(reportFolderPath)` instead of `reportFolderPath != null` in the following if statement would be a more clear fix.

**Review by JoeRobich — APPROVED** [review]
Thanks for fixing this issue! Only one suggestion, but I would also accept this fix as is.

File: src/ReportWriter.cs (hunk 1 above)
Comment (Styxxy) [reply src/ReportWriter.cs:21]: I considered it, but went for the string empty comparison as there was a null check in the next if statement, and I didn't want to change that semantic (otherwise the null check would be irrelevant).
Can change though if you prefer ;-).

Comment (Styxxy) [reply src/ReportWriter.cs:21]: Ok good idea. Didn't properly check if the variable was used apart from the check to create a directory (which isn't). Will change.

**Review by JoeRobich — APPROVED** [review]
Thanks again. I'll shepard this through our flaky CI today.

**Comment by Styxxy** [comment]
Thanks @JoeRobich , was wondering if it was something that I broke (which seemed unlikely with the very small code change) :) .
